version: '3'
services:
  nginx:
    image: "nginx"
    ports:
      - "80:80" #The left one is your device, right one is inside the container
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/var/www/website/index.html
    networks:
      - esnet

volumes:
  esdata1:
    driver: local

networks:
  esnet:
